### PR TITLE
Fix compilation error on arm7 architecture. Compiles and runs on Fedora 29 on Pi 3.

### LINKED ISSUE #3509: Build on armv7l fails
## Expected Behavior

Builds

## Actual Behavior

```
[  213s] [  0%] Building CXX object src/CMakeFiles/hpx.dir/exception.cpp.o
[  213s] cd /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/build/src && /usr/bin/c++  -DBOOST_DISABLE_ASSERTS -DHPX_COMPONENT_NAME=hpx -DHPX_DISABLE_ASSERTS -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_GNU_SOURCE -Dhpx_EXPORTS -I/home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1 -I/home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/build  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=trampolines -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -std=c++17 -o CMakeFiles/hpx.dir/exception.cpp.o -c /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/src/exception.cpp
[  222s] In file included from /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/hpx/runtime.hpp:12,
[  222s]                  from /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/src/exception.cpp:14:
[  222s] /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/hpx/lcos/local/spinlock.hpp: In member function 'bool hpx::lcos::local::spinlock::acquire_lock()':
[  222s] /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/hpx/lcos/local/spinlock.hpp:112:31: error: 'BOOST_INTERLOCKED_EXCHANGE' was not declared in this scope
[  222s]              std::uint64_t r = BOOST_INTERLOCKED_EXCHANGE(&v_, 1);
[  222s]                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
[  222s] /home/abuild/rpmbuild/BUILD/hpx-1.2.0-rc1/hpx/lcos/local/spinlock.hpp:112:31: note: suggested alternative: 'BOOST_INTRUSIVE_DOCIGN'
[  222s]              std::uint64_t r = BOOST_INTERLOCKED_EXCHANGE(&v_, 1);
[  222s]                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
[  222s]                                BOOST_INTRUSIVE_DOCIGN
[  233s] make[2]: *** [src/CMakeFiles/hpx.dir/build.make:79: src/CMakeFiles/hpx.dir/exception.cpp.o] Error 1
```

## Steps to Reproduce the Problem

Try to build on armv7l, details [here](https://github.com/STEllAR-GROUP/hpx/files/2531927/build_arm7.txt).

## Specifications

  - HPX Version: 1.2.0-rc1
  - Platform (compiler, OS): gcc-8.2.1, OpenSuse

### PR DESCRIPTION
**Pull request by diehlpk**
HPX, compiles on arm7 again, when using gcc 8.2 and the dependencies provided by Fedora 29.  One has to use the -DHPX_WITH_GENERIC_CONTEXT_COROUTINES=ON too.

Fixes #3509

## Proposed Changes

  - Adapt the define directive on the spinlock.hpp to compile again on arm7

## Any background context you want to provide?

```
[pi@alpi build]$ ./bin/fibonacci 
fibonacci(10) == 55
elapsed time: 0.008454 [s]
```

### CODE REVIEW

**Comment by junghans** [comment]
Could you test this patch on your fork of the openSUSE package, too?

**Comment by diehlpk** [comment]
> Could you test this patch on your fork of the openSUSE package, too?

Yes.

**Comment by junghans** [comment]
I did some test builds on Fedora as well:
https://koji.fedoraproject.org/koji/taskinfo?taskID=31495042
https://koji.fedoraproject.org/koji/taskinfo?taskID=31495047
https://koji.fedoraproject.org/koji/taskinfo?taskID=31495045

**Comment by diehlpk** [comment]
> I did some test builds on Fedora as well:
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495042
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495047
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495045

https://koji.fedoraproject.org/koji/taskinfo?taskID=31487748

**Comment by msimberg** [comment]
@diehlpk, the CUDA failures are unrelated to this PR (it's a bit subtle, but I haven't marked them as "required" exactly because the build also fails on master). Other failures are unlikely to be caused by this PR, but are rather random failures that are already in master. I've just restarted the CircleCI builds. Same applies to your other PRs.

**Comment by junghans** [comment]
> I did some test builds on Fedora as well:
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495042
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495047
> https://koji.fedoraproject.org/koji/taskinfo?taskID=31495045

https://bodhi.fedoraproject.org/updates/FEDORA-2018-9be1052cf8
https://bodhi.fedoraproject.org/updates/FEDORA-2018-7c77e5ef2b

**Comment by msimberg** [comment]
@diehlpk do you know more about why this fixes the ARM build? The additional `&& !defined(__arm__)` was apparently added for building on a raspberry pi (https://github.com/STEllAR-GROUP/hpx/commit/e7a89d859d3c87811931b35bbdfd3c887f6f60a7), so I'm wondering what changed. Is there e.g. a fix in newer Boosts or something like that?

**Comment by diehlpk** [comment]
> the problem is with us: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/lcos/local/spinlock.hpp#L31
> We don't include the header if `__arm__` is defined.
> This should be overhauled, I think.

@msimberg I was just following what @sithhell recommend and it was working. It may could be related due to a newer boost version, but to be honest, I did not investigate more.
