### ISSUE TITLE
asio fails to build with CUDA 10.0

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#5306]
As reported by @G-071:
```
home/daissgr/workshop/KokkosPower-Redux/build/hpx/include/asio/execution/blocking.hpp(835): error: expected an expression

At end of source: warning: parsing restarts here after previous syntax error

At end of source: error: expected an expression

/home/daissgr/workshop/KokkosPower-Redux/build/hpx/include/asio/execution/blocking.hpp(835): error: expected a ";"

/home/daissgr/workshop/KokkosPower-Redux/build/hpx/include/asio/execution/blocking.hpp(835): error: expected a "}"

/home/daissgr/workshop/KokkosPower-Redux/build/hpx/include/asio/execution/blocking.hpp(835): error: expected a "}"
```

Definitely works with CUDA >= 11, probably also with 10.2. I'm closing this as wontfix unless someone has a big need for having this fixed for older compilers. Reporting it here just in case someone else has the same problem. See #5305.
