### ISSUE TITLE
v1.11.0 fails to build with asio-1.38.2

### ISSUE THREAD

**Issue by junghans** [STEllAR-GROUP/hpx#7428]
From https://bugzilla.redhat.com/show_bug.cgi?id=2504129, I triggered it again here: https://koji.fedoraproject.org/koji/taskinfo?taskID=148633214

```
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/io_service/src/io_service_pool.cpp: In member function ‘void hpx::util::io_service_pool::wait_locked()’:
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/io_service/src/io_service_pool.cpp:262:34: error: ‘class asio::io_context’ has no member named ‘reset’; did you mean ‘restart’?
  262 |                 io_services_[i]->reset();
      |                                  ^~~~~
      |                                  restart
```

[build log](https://github.com/user-attachments/files/30662064/build_x86.log.zip)

**Comment by hkaiser** [comment]
@junghans thanks for reporting. I don't think we will fix this for V1.11, it's already fixed for the upcoming v2.0 (to be released soon). Can you simply let it use an older version of ASIO (`cmake -DHPX_WITH_ASIO_TAG=asio-1.33.0 ...` or similar)?

**Comment by junghans** [comment]
Fedora Rawhide only has one version of the asio package....

**Comment by hkaiser** [comment]
> Fedora Rawhide only has one version of the asio package....

Would this patch help?
```diff
diff --git a/libs/core/io_service/src/io_service_pool.cpp b/libs/core/io_service/src/io_service_pool.cpp
index 44eb3318c04..2b667dae451 100644
--- a/libs/core/io_service/src/io_service_pool.cpp
+++ b/libs/core/io_service/src/io_service_pool.cpp
@@ -17,6 +17,7 @@
 #include <hpx/modules/logging.hpp>
 
 #include <asio/io_context.hpp>
+#include <asio/version.hpp>
 
 #include <cstddef>
 #include <memory>
@@ -259,7 +260,11 @@ namespace hpx::util {
             for (std::size_t i = 0; i < pool_size_; ++i)
             {
                 work_.emplace_back(initialize_work(*io_services_[i]));
+#if ASIO_VERSION >= 103400
+                io_services_[i]->restart();
+#else
                 io_services_[i]->reset();
+#endif
             }
 
             continue_barrier_->wait();
```

**Comment by junghans** [comment]
Thanks, test build: https://koji.fedoraproject.org/koji/taskinfo?taskID=148696466

**Comment by hkaiser** [comment]
> Thanks, test build: https://koji.fedoraproject.org/koji/taskinfo?taskID=148696466

Looks like that there are more fixes needed. I'll see what I can do.

**Comment by junghans** [comment]
Yeah
```
In file included from /builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/src/map_hostnames.cpp:8:
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:53:61: error: ‘iterator’ in ‘asio::ip::tcp::resolver’ {aka ‘class asio::ip::basic_resolver<asio::ip::tcp>’} does not name a type
   53 |     using endpoint_iterator_type = asio::ip::tcp::resolver::iterator;
      |                                                             ^~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:55:19: error: ‘endpoint_iterator_type’ does not name a type
   55 |     [[nodiscard]] endpoint_iterator_type HPX_CORE_EXPORT connect_begin(
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:63:19: error: ‘endpoint_iterator_type’ does not name a type
   63 |     [[nodiscard]] endpoint_iterator_type connect_begin(
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:69:26: error: ‘endpoint_iterator_type’ does not name a type
   69 |     [[nodiscard]] inline endpoint_iterator_type connect_end()
      |                          ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:74:19: error: ‘endpoint_iterator_type’ does not name a type
   74 |     [[nodiscard]] endpoint_iterator_type HPX_CORE_EXPORT accept_begin(
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:83:19: error: ‘endpoint_iterator_type’ does not name a type
   83 |     [[nodiscard]] endpoint_iterator_type accept_begin(
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/hpx-1.11.0-build/hpx-1.11.0/libs/core/asio/include/hpx/asio/asio_util.hpp:89:26: error: ‘endpoint_iterator_type’ does not name a type
   89 |     [[nodiscard]] inline endpoint_iterator_type accept_end()    //-V524
      |                          ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by junghans** [comment]
Fix pending with patch from #7463: https://koji.fedoraproject.org/koji/taskinfo?taskID=149335691

**Comment by hkaiser** [comment]
This was fixed by merging #7463
