### ISSUE TITLE
hpx fails to build with asio-1.34.2: error: no type named 'iterator' in 'asio::ip::basic_resolver<asio::ip::tcp>'

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#6747]
```
In file included from /wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:14:
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:53:61: error: no type named 'iterator' in 'asio::ip::basic_resolver<asio::ip::tcp>'
   53 |     using endpoint_iterator_type = asio::ip::tcp::resolver::iterator;
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:55:19: error: unknown type name 'endpoint_iterator_type'
   55 |     [[nodiscard]] endpoint_iterator_type HPX_CORE_EXPORT connect_begin(
      |                   ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:63:19: error: unknown type name 'endpoint_iterator_type'
   63 |     [[nodiscard]] endpoint_iterator_type connect_begin(
      |                   ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:69:26: error: unknown type name 'endpoint_iterator_type'
   69 |     [[nodiscard]] inline endpoint_iterator_type connect_end()
      |                          ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:74:19: error: unknown type name 'endpoint_iterator_type'
   74 |     [[nodiscard]] endpoint_iterator_type HPX_CORE_EXPORT accept_begin(
      |                   ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:83:19: error: unknown type name 'endpoint_iterator_type'
   83 |     [[nodiscard]] endpoint_iterator_type accept_begin(
      |                   ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/include/hpx/asio/asio_util.hpp:89:26: error: unknown type name 'endpoint_iterator_type'
   89 |     [[nodiscard]] inline endpoint_iterator_type accept_end()    //-V524
      |                          ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:58:25: error: no member named 'from_string' in 'asio::ip::address_v4'
   58 |             address_v4::from_string(addr.c_str(), ec);
      |             ~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:68:29: error: no member named 'from_string' in 'asio::ip::address_v6'
   68 |                 address_v6::from_string(addr.c_str(), ec);
      |                 ~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:111:33: error: expected ';' after expression
  111 |             tcp::resolver::query query(hostname, std::to_string(port));
      |                                 ^
      |                                 ;
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:111:28: error: no member named 'query' in 'asio::ip::basic_resolver<asio::ip::tcp>'
  111 |             tcp::resolver::query query(hostname, std::to_string(port));
      |             ~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:111:34: error: use of undeclared identifier 'query'
  111 |             tcp::resolver::query query(hostname, std::to_string(port));
      |                                  ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:113:38: error: no type named 'iterator' in 'asio::ip::basic_resolver<asio::ip::tcp>'
  113 |             asio::ip::tcp::resolver::iterator it = resolver.resolve(query);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:113:69: error: use of undeclared identifier 'query'
  113 |             asio::ip::tcp::resolver::iterator it = resolver.resolve(query);
      |                                                                     ^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:118:45: error: no member named 'iterator' in 'asio::ip::basic_resolver<asio::ip::tcp>'; did you mean 'operator'?
  118 |                 while (it != tcp::resolver::iterator() &&
      |                              ~~~~~~~~~~~~~~~^~~~~~~~
      |                                             operator
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:118:45: error: no member named 'operator()' in 'asio::ip::basic_resolver<asio::ip::tcp>'
  118 |                 while (it != tcp::resolver::iterator() &&
      |                              ~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:152:33: error: expected ';' after expression
  152 |             tcp::resolver::query query(asio::ip::host_name(), "");
      |                                 ^
      |                                 ;
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:152:28: error: no member named 'query' in 'asio::ip::basic_resolver<asio::ip::tcp>'
  152 |             tcp::resolver::query query(asio::ip::host_name(), "");
      |             ~~~~~~~~~~~~~~~^
/wrkdirs/usr/ports/devel/hpx/work/hpx-1.10.0/libs/core/asio/src/asio_util.cpp:152:34: error: use of undeclared identifier 'query'
  152 |             tcp::resolver::query query(asio::ip::host_name(), "");
      |                                  ^
```

[log](https://pkg-status.freebsd.org/beefy22/data/142amd64-default/853f568b31ec/logs/hpx-1.10.0_5.log)

Versions: 1.10.0, 1.11.0
FreeBSD 14.3

**Comment by hkaiser** [comment]
This is a known issue and has been fixed on master (see: https://github.com/STEllAR-GROUP/hpx/pull/6731). We will add this fix as part of a V1.11.1 point release.

**Comment by miyanyan** [comment]
Hi, will there be a V1.11.1 release, or just new V2.0.0 release in https://github.com/TheHPXProject/hpx/pull/7560

**Comment by hkaiser** [comment]
> Hi, will there be a V1.11.1 release, or just new V2.0.0 release in [#7560](https://github.com/TheHPXProject/hpx/pull/7560)

The plan is to have a release of HPX V2.0.0 only. Are you waiting for v1.11.1? If yes, what's your reasoning?

**Comment by miyanyan** [comment]
> Are you waiting for v1.11.1?

I'm waiting for the new release that solved asio issues. I'm ok to V2.0.0, just curious about the 1.11.1 milestone you marked last year

**Comment by hkaiser** [comment]
> > Are you waiting for v1.11.1?
> 
> I'm waiting for the new release that solved asio issues. I'm ok to V2.0.0, just curious about the 1.11.1 milestone you marked last year

We're planning to have a first release candidate out by the of the month. We'd very much appreciate any feedback you can give once that happened.
