### ISSUE TITLE
redefinition of boost::detail::spinlock

### ISSUE THREAD

**Issue by BryanFlynt** [STEllAR-GROUP/hpx#2470]
I've tried to build on 2 different OS, 3 different compilers and multiple Boost versions and have yet to succeed.  The most prolific error I get is the redefinition of the boost spinlock.  Here are the details of this particular setup. (Note: I get the same error but on the 4th source file when using GCC 4.8)

System: OpenSUSE 13.1 + GCC 6.3.0 + Boost 1.63.0 + HPX 0.9.99

>> make
Scanning dependencies of target hpx
[  0%] Building CXX object src/CMakeFiles/hpx.dir/error_code.cpp.o
[  0%] Building CXX object src/CMakeFiles/hpx.dir/exception.cpp.o
In file included from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/lcos/local/spinlock.hpp:30:0,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/runtime.hpp:11,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/src/exception.cpp:13:
/home/bflynt/opt/boost/boost_1_63_0/boost/smart_ptr/detail/spinlock_sync.hpp:30:7: error: redefinition of ‘class boost::detail::spinlock’
 class spinlock
       ^~~~~~~~
In file included from /home/bflynt/opt/boost/boost_1_63_0/boost/smart_ptr/detail/spinlock.hpp:47:0,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/smart_ptr/shared_ptr.hpp:35,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/shared_ptr.hpp:17,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/exception/detail/shared_ptr.hpp:13,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/exception/info.hpp:18,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/exception/detail/exception_ptr.hpp:20,
                 from /home/bflynt/opt/boost/boost_1_63_0/boost/exception_ptr.hpp:9,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/throw_exception.hpp:17,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/exception_fwd.hpp:69,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/error_code.hpp:14,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/src/exception.cpp:9:
/home/bflynt/opt/boost/boost_1_63_0/boost/smart_ptr/detail/spinlock_std_atomic.hpp:27:7: error: previous definition of ‘class boost::detail::spinlock’
 class spinlock
       ^~~~~~~~
In file included from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/lcos/local/spinlock.hpp:30:0,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/runtime.hpp:11,
                 from /home/bflynt/opt/hpx/builds/hpx_0.9.99/src/exception.cpp:13:
/home/bflynt/opt/hpx/builds/hpx_0.9.99/hpx/util/spinlock.hpp: In constructor ‘hpx::util::spinlock::spinlock(const char*)’:

Any Ideas ???

**Comment by biddisco** [comment]
it’s clear you’re using boost163, but you don’t mention which hpx you have. Can I suggest you use the master branch from git rather than an older 0.99 version tarball (if that’s where you got it from). Also please post the full cmake invocation that you use to  cmake so that we have more of an idea of what’s wrong.

Boost 1.63 is quite new, so if you use an hpx that was released before that came out, there’s always a chance of this kind of bug

JB

**Comment by BryanFlynt** [comment]
You are correct.  
The latest master branch from git allows me to compile using both GCC 4.8 and 6.3 with boost 1.63.  

I did encounter a different error on my new Mac system using boost 1.63.0 but it appears to be a separate issue so I'll put that in separate.  Thanks

**Comment by hkaiser** [comment]
This seems to have been fixed. I'm closing this ticket now, feel free to reopen, if necessary.
