### ISSUE TITLE
quicksort example doesn't compile

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#273]
**[reported by maciek]** _[Trac time Thu Dec  1 16:23:28 2011]_ Quicksort example fails to compile in 0.7.0-rc1 with the following error (gcc-4.5.3, boost-1.47.0):

```
[ 91%] Building CXX object examples/quickstart/CMakeFiles/quicksort_exe.dir/quicksort.cpp.o
/home/maciek/Projects/parallex/tags/hpx/0.7.0-rc1/examples/quickstart/quicksort.cpp: In function ‘size_t partition(uint32_t*, size_t, size_t)’:
/home/maciek/Projects/parallex/tags/hpx/0.7.0-rc1/examples/quickstart/quicksort.cpp:53:38: error: uninitialized const ‘less_’
```
