### ISSUE TITLE
Building HPX with hwloc 2.0.0 fails

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/hpx#3161]
HPX fails to compile with hwloc 2.0.0 with error message: `error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'`. This is likely related to hwloc 2.0.0 itself and I expect it to be reproducible on any HPX setup that attempts to use it.

Compile log:
```
[1/180] Building CXX object src/CMakeFiles/hpx.dir/version.cpp.o
FAILED: src/CMakeFiles/hpx.dir/version.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/version.cpp.o -MF src/CMakeFiles/hpx.dir/version.cpp.o.d -o src/CMakeFiles/hpx.dir/version.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/version.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/version.cpp:19:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime_fwd.hpp:14:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/basename_registration.hpp:14:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
[2/180] Building CXX object src/CMakeFiles/hpx.dir/state.cpp.o
FAILED: src/CMakeFiles/hpx.dir/state.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/state.cpp.o -MF src/CMakeFiles/hpx.dir/state.cpp.o.d -o src/CMakeFiles/hpx.dir/state.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/state.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/state.cpp:10:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime.hpp:13:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/performance_counters/counters.hpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
[3/180] Building CXX object src/CMakeFiles/hpx.dir/exception.cpp.o
FAILED: src/CMakeFiles/hpx.dir/exception.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/exception.cpp.o -MF src/CMakeFiles/hpx.dir/exception.cpp.o.d -o src/CMakeFiles/hpx.dir/exception.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/exception.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/exception.cpp:14:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime.hpp:13:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/performance_counters/counters.hpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
[4/180] Building CXX object src/CMakeFiles/hpx.dir/runtime.cpp.o
FAILED: src/CMakeFiles/hpx.dir/runtime.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/runtime.cpp.o -MF src/CMakeFiles/hpx.dir/runtime.cpp.o.d -o src/CMakeFiles/hpx.dir/runtime.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/runtime.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/runtime.cpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/performance_counters/counters.hpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
[5/180] Building CXX object src/CMakeFiles/hpx.dir/hpx_init.cpp.o
FAILED: src/CMakeFiles/hpx.dir/hpx_init.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/hpx_init.cpp.o -MF src/CMakeFiles/hpx.dir/hpx_init.cpp.o.d -o src/CMakeFiles/hpx.dir/hpx_init.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/hpx_init.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/hpx_init.cpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/apply.hpp:10:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
[6/180] Building CXX object src/CMakeFiles/hpx.dir/runtime_impl.cpp.o
FAILED: src/CMakeFiles/hpx.dir/runtime_impl.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DDEBUG -DHPX_COMPONENT_NAME=hpx -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_DEBUG -D_GNU_SOURCE -Dhpx_EXPORTS -I/Users/parsa/Documents/hpx/code/hpx/repo -isystem /usr/local/include -I/usr/local/Cellar/hwloc/2.0.0/include -I. -pthread -ftemplate-depth=256 -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC   -std=c++1z -MD -MT src/CMakeFiles/hpx.dir/runtime_impl.cpp.o -MF src/CMakeFiles/hpx.dir/runtime_impl.cpp.o.d -o src/CMakeFiles/hpx.dir/runtime_impl.cpp.o -c /Users/parsa/Documents/hpx/code/hpx/repo/src/runtime_impl.cpp
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/src/runtime_impl.cpp:8:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/performance_counters/counters.hpp:11:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/future.hpp:12:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/lcos/detail/future_data.hpp:15:
In file included from /Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/thread_executor.hpp:14:
/Users/parsa/Documents/hpx/code/hpx/repo/hpx/runtime/threads/topology.hpp:70:30: error: use of undeclared identifier 'HWLOC_MEMBIND_REPLICATE'
        membind_replicate  = HWLOC_MEMBIND_REPLICATE,
                             ^
1 error generated.
```

## Steps to Reproduce the Problem

```sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install hwloc boost gperftools ninja
git clone --depth=1 https://github.com/stellar-group/hpx.git repo
mkdir build
cd build
cmake -G'Ninja' -DCMAKE_BUILD_TYPE=Debug  ../repo
cd build
ninja hello_world_exe
```

## Specifications

  - HPX Version: 922deeb0bd
  - Platform (compiler, OS): Apple Clang, macOS High Sierra
  - hwloc 2.0.0, Boost 1.66.0, gperftools 2.6.3
