### ISSUE TITLE
tests/regressions/block_matrix/matrix.hh won't compile with GCC 4.8.1

### ISSUE THREAD

**Issue by jlippuner** [STEllAR-GROUP/hpx#881]
Running `make tests` with GCC 4.8.1 results in the following error:

```
In file included from /home/jlippuner/hpx/hpx-src/tests/regressions/block_matrix/block_matrix.hh:10:0,
                 from /home/jlippuner/hpx/hpx-src/tests/regressions/block_matrix/algorithms.hh:9,
                 from /home/jlippuner/hpx/hpx-src/tests/regressions/block_matrix/algorithms.cc:6:
/home/jlippuner/hpx/hpx-src/tests/regressions/block_matrix/matrix.hh: In member function ‘vector_t& vector_t::operator=(const vector_t&)’:
/home/jlippuner/hpx/hpx-src/tests/regressions/block_matrix/matrix.hh:42:53: error: no return statement in function returning non-void [-Werror=return-type]
   vector_t& operator=(const vector_t&) { assert(0); }
```
