### ISSUE TITLE
Build HPX 1.2 with boost 1.69

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#3638]
## Expected Behavior

HPX should build with boost 1.69

## Actual Behavior

```
[ 10%] Building CXX object src/CMakeFiles/hpx.dir/throw_exception.cpp.o
/home/diehlpk/Compile/hpx-1.2.0/src/throw_exception.cpp: In function ‘std::__exception_ptr::exception_ptr hpx::detail::get_exception(boost::system::error_code, const string&, hpx::throwmode, const string&, const string&, long int, const string&)’:
/home/diehlpk/Compile/hpx-1.2.0/src/throw_exception.cpp:54:30: error: no matching function for call to ‘hpx::exception::exception(boost::system::error_code&)’
             hpx::exception(ec),
                              ^
In file included from /home/diehlpk/Compile/hpx-1.2.0/src/throw_exception.cpp:9:
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:77:9: note: candidate: ‘hpx::exception::exception(hpx::error, const string&, hpx::throwmode)’
         exception(error e, std::string const& msg, throwmode mode = plain);
         ^~~~~~~~~
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:77:9: note:   candidate expects 3 arguments, 1 provided
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:64:9: note: candidate: ‘hpx::exception::exception(hpx::error, const char*, hpx::throwmode)’
         exception(error e, char const* msg, throwmode mode = plain);
         ^~~~~~~~~
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:64:9: note:   candidate expects 3 arguments, 1 provided
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:51:18: note: candidate: ‘hpx::exception::exception(const boost::system::system_error&)’
         explicit exception(boost::system::system_error const& e);
                  ^~~~~~~~~
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:51:18: note:   no known conversion for argument 1 from ‘boost::system::error_code’ to ‘const boost::system::system_error&’
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:48:18: note: candidate: ‘hpx::exception::exception(hpx::error)’
         explicit exception(error e = success);
                  ^~~~~~~~~
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:48:18: note:   no known conversion for argument 1 from ‘boost::system::error_code’ to ‘hpx::error’
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:41:32: note: candidate: ‘hpx::exception::exception(const hpx::exception&)’
     class HPX_EXCEPTION_EXPORT exception : public boost::system::system_error
                                ^~~~~~~~~
/home/diehlpk/Compile/hpx-1.2.0/hpx/exception.hpp:41:32: note:   no known conversion for argument 1 from ‘boost::system::error_code’ to ‘const hpx::exception&’
make[3]: *** [src/CMakeFiles/hpx.dir/build.make:154: src/CMakeFiles/hpx.dir/throw_exception.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:1829: src/CMakeFiles/hpx.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:413: CMakeFiles/core.dir/rule] Error 2
make: *** [Makefile:305: core] Error 2
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Download HPX 1.2
  1. Compile boost 1.69
  1. Compile HPX

## Specifications

... Please describe your environment

  - HPX Version: 1.2 
  - Platform (compiler, OS): gcc 8.2.1, Fedora 29

**Comment by diehlpk** [comment]
Master compiles with https://github.com/STEllAR-GROUP/hpx/commit/fde86e38dcc2d4941b91cc75a84948a4a5f8e3d6#diff-eaefb7cfedcbd7092bb906067dd0f2b7 and we need a diff for HPX 1.2 to prepare it for Fedora 30

**Comment by hkaiser** [comment]
@diehlpk Here is the actual diff: https://github.com/STEllAR-GROUP/hpx/commit/fde86e38dcc2d4941b91cc75a84948a4a5f8e3d6.diff
