### PR TITLE
Fix OSX build

### PR DESCRIPTION
**Pull request by jfbastien**
Linker was complaining because of multiple definitions. The header was being included in multiple places, and they were each getting and exporting their own instance of the mutex.

This was broken in 0d9d74d1cc78aa738d66bbb04fb5d3e600675ad4

### CODE REVIEW

**Comment by brycelelbach** [comment]
In C++17 we could've just made it inline. But this looks fine, presuming that CI comes back green.

File: hpx/util/logging/format/formatter/high_precision_time.hpp [hunk 1]
```diff
@@ -36,7 +36,6 @@
 #else
 #include <hpx/lcos/local/spinlock.hpp>
 #include <mutex>
-hpx::lcos::local::spinlock gmtime_call_mutex;
```
Comment (brycelelbach) [inline hpx/util/logging/format/formatter/high_precision_time.hpp]: In C++17 we could have just added inline here.

**Comment by hkaiser** [comment]
@brycelelbach: we try to stick to C++11 (for unguarded code), so this fix is correct.

File: hpx/util/logging/format/formatter/high_precision_time.hpp [hunk 2]
```diff
@@ -105,7 +104,8 @@ template<class convert = do_convert_format::prepend> struct high_precision_time_
         // fall back to non-thread-safe version on other platforms
         std::tm local_tm;
         {
-            std::unique_lock<hpx::lcos::local::spinlock> ul(gmtime_call_mutex);
+            static hpx::lcos::local::spinlock mutex;
+            std::unique_lock<hpx::lcos::local::spinlock> ul(mutex);
```
Comment (brycelelbach) [inline hpx/util/logging/format/formatter/high_precision_time.hpp]: This looks fine; note that this code is surrounded in the same #ifdef/#endif block as the above diff, although the #ifdef/#endif aren't visible in this patch..

**Comment by brycelelbach** [comment]
@hkaiser: I know :). Just mentioning it.

**Comment by brycelelbach** [comment]
Hrm, why is the AppVeyor build failing?

**Comment by brycelelbach** [comment]
Hrm, why is the AppVeyor build failing?
