### ISSUE TITLE
Spack Build Error with ROCm 5.7.0

### ISSUE THREAD

**Issue by jholmen** [STEllAR-GROUP/hpx#6405]
## Expected Behavior

Successful HPX 1.9.1 builds with ROCm 5.7.0.

## Actual Behavior

Spack builds fail with the below:

```
/tmp/jholmen/spack-stage/spack-stage-hpx-1.9.1-am4jnczyyvsp3fesiqign5o67rbwkpf4/spack-src/libs/core/program_options/src/value_semantic.cpp:382:18: error: no viable constructor or deduction guide for deduction of template arguments of 'set'
	std::set alternatives_set(m_alternatives.begin(), m_alternatives.end());
```

Full log: [spack-install-output.txt](https://github.com/STEllAR-GROUP/hpx/files/13865015/spack-install-output.txt)

## Steps to Reproduce the Problem

(1) Load the environment:

```
module load PrgEnv-amd
module load cpe/23.09
module load amd/5.7.0
```

(2) Clone Spack:

```
git clone --depth=100 --branch=develop-2023-12-31 https://github.com/spack/spack.git
cd spack
. share/spack/setup-env.sh
```

(3) Setup system packages:

```
spack compiler find
spack external find hip llvm-amdgpu hsa-rocr-dev
```

(3) Install HPX:

```
spack install hpx@1.9.1%rocmcc@5.7.0
```

## Specifications

  - HPX Version: 1.9.1
  - Platform (compiler, OS): ROCm 5.7.0, OLCF Frontier
  - System GCC Version: 7.5.0
  
  Module List:

```  
craype-x86-trento
libfabric/1.15.2.0
craype-network-ofi
xpmem/2.6.2-2.5_2.22__gd067c3f.shasta
PrgEnv-amd/8.4.0
darshan-runtime/3.4.0
hsi/default
DefApps/default
cray-dsmml/0.2.2
cray-libsci/23.09.1.1
cray-pmi/6.1.12
craype/2.7.23
perftools-base/23.09.0
cpe/23.09
amd/5.7.0
cray-mpich/8.1.27
 ```

**Comment by hkaiser** [comment]
That was fixed by merging #6406
