### PR TITLE
Use object libraries for modules

### LINKED ISSUE #4135: Use object libraries for modules
We should consider using [object libraries](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries) for creating `libhpx` out of the modules. This should be significantly cleaner and may let us avoid the `force_linking` mechanisms. However, we would need CMake 3.12 for this (object libraries exist before that, but are somewhat crippled). I'm tentatively adding this to next year's release, when I think we could reasonably bump the minimum CMake version to 3.12 or higher.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #4135. Still a draft as I think this will have the same problems as in #4649 (i.e. long configuration times). At least I have not done anything about them. Profiling on Linux gives little useful information and the configuration times are mostly unchanged, so I'll first see what the GitHub actions builders say. @hkaiser at some point I'd need you to test this on Windows, but this is not urgent at all. I'm just opening this up to get this started again.

### CODE REVIEW

**Comment by msimberg** [comment]
@K-ballo since it seems you've been trying out this branch, have you noticed anything regarding the CMake configuration/generation times? I.e. is it still as bad as @hkaiser reported earlier or do you not notice much of a difference?

**Comment by K-ballo** [comment]
> have you noticed anything regarding the CMake configuration/generation times?

With the default configuration flags, the generation phase is about 13 seconds longer on my machine (~33s vs ~20s).
There is no noticeable difference when configuring only core.

**Comment by msimberg** [comment]
@hkaiser I've disabled object libraries for the `hpx_full` now so the circular dependencies don't matter at the moment. Would you mind trying this out again to see if it has any effect on the configuration times? Unfortunately I think it won't have much of a difference, but it'd be nice to get this in even in a limited form.

**Comment by hkaiser** [comment]
@msimberg sorry, it took a while to get back to this. This seems to work just fine with VS, there are no significant timing differences to master, neither configuration, nor build times.

**Comment by msimberg** [comment]
> @msimberg sorry, it took a while to get back to this. This seems to work just fine with VS, there are no significant timing differences to master, neither configuration, nor build times.

No problem, and thanks for testing again!

There are two remaining problems: pkgconfig file generation and switch_to_fiber. `switch_to_fiber.obj` does not seem to be built anymore now that the modules are object libraries. CMake is for some reason treating them differently. Did that work for you locally? Pkgconfig files are not generated correctly at the moment, and as I've said earlier I'd prefer to drop support for them. If someone would be interested in maintaining them that'd be helpful.

**Comment by hkaiser** [comment]
> There are two remaining problems: pkgconfig file generation and switch_to_fiber. `switch_to_fiber.obj` does not seem to be built anymore now that the modules are object libraries. CMake is for some reason treating them differently. Did that work for you locally? 

I didn't try :/ Will check.

> Pkgconfig files are not generated correctly at the moment, and as I've said earlier I'd prefer to drop support for them. If someone would be interested in maintaining them that'd be helpful.

I'll ask @stevenrbrandt if he would be interested. Would there be an option to make those independent of the build system (i.e. static)?

**Comment by stevenrbrandt** [comment]
@hkaiser @msimberg What is wrong with the pkgconfig files? They work for me. Regardless, they have been useful for me in a number of contexts.

**Comment by msimberg** [comment]
> @hkaiser @msimberg What is wrong with the pkgconfig files? They work for me. Regardless, they have been useful for me in a number of contexts.

There's nothing wrong with them on master. The problem is that this breaks them. Object libraries end up in the linker flags as completely nonsense (CMake-specific) libraries. It may be possible to filter them out, but I don't know if that'd work with all CMake versions.

> I'll ask @stevenrbrandt if he would be interested. Would there be an option to make those independent of the build system (i.e. static)?

I'm not sure. I'll have a think about this.

**Comment by stevenrbrandt** [comment]
I guess I'm not too worried about how they work, so long as I still have access to them. I can try to help maintain them if need be.

**Comment by msimberg** [comment]
> I guess I'm not too worried about how they work, so long as I still have access to them. I can try to help maintain them if need be.

I've just pushed a fix which seems to work at least with CMake 3.19. I suppose you wouldn't be too bothered if this would require a pretty recent CMake (we're anyway considering bumping the minimum to 3.17 in #5165) and/or it wouldn't always work with every version of CMake? The fix currently filters out what seems to be a CMake implementation detail and that may change in future versions and stop this from working, but hopefully we can simply filter out something else if that does end up changing.

**Comment by stevenrbrandt** [comment]
@msimberg recent cmakes are fine :)

**Comment by hkaiser** [comment]
@msimberg I tried again on Windows, this time with `HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=On`. This results in linker errors for hpx_core:
```
45>------ Rebuild All started: Project: hpx_core, Configuration: Debug x64 ------
45>Building Custom Rule D:/Devel/hpx/worktree/feature1/libs/CMakeLists.txt
45>dummy.cpp
45>LINK : error LNK2001: unresolved external symbol switch_to_fiber
45>D:/Devel/hpx/worktree/feature1/build/Debug/lib/hpx_cored.lib : fatal error LNK1120: 1 unresolved externals
```
The corresponding object file was successfully compiled earlier, however:
```
33>------ Rebuild All started: Project: hpx_coroutines, Configuration: Debug x64 ------
33>Generating switch_to_fiber.obj
34>Building Custom Rule D:/Devel/hpx/worktree/feature1/libs/core/testing/CMakeLists.txt
33> Assembling: D:/Devel/hpx/worktree/feature1/libs/core/coroutines/src/switch_to_fiber.asm
33>Building Custom Rule D:/Devel/hpx/worktree/feature1/libs/core/coroutines/CMakeLists.txt
33>unity_0_cxx.cxx
33>coroutine_impl.cpp
33>coroutine_self.cpp
33>hpx_coroutines.vcxproj -> D:\Devel\hpx\worktree\feature1\build\libs\core\coroutines\hpx_coroutines.dir\Debug\hpx_coroutines.lib
```
(side note: it's not quite clear why the two `.cpp` files are compiled separately outside the unity build - but that's unrelated).

**Comment by msimberg** [comment]
> @msimberg I tried again on Windows, this time with `HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=On`. This results in linker errors for hpx_core:
> 
> ```
> 45>------ Rebuild All started: Project: hpx_core, Configuration: Debug x64 ------
> 45>Building Custom Rule D:/Devel/hpx/worktree/feature1/libs/CMakeLists.txt
> 45>dummy.cpp
> 45>LINK : error LNK2001: unresolved external symbol switch_to_fiber
> 45>D:/Devel/hpx/worktree/feature1/build/Debug/lib/hpx_cored.lib : fatal error LNK1120: 1 unresolved externals
> ```
> 
> The corresponding object file was successfully compiled earlier, however:
> 
> ```
> 33>------ Rebuild All started: Project: hpx_coroutines, Configuration: Debug x64 ------
> 33>Generating switch_to_fiber.obj
> 33> Assembling: D:/Devel/hpx/worktree/feature1/libs/core/coroutines/src/switch_to_fiber.asm
> 33>Building Custom Rule D:/Devel/hpx/worktree/feature1/libs/core/coroutines/CMakeLists.txt
> 33>unity_0_cxx.cxx
> 33>coroutine_impl.cpp
> 33>coroutine_self.cpp
> 33>hpx_coroutines.vcxproj -> D:\Devel\hpx\worktree\feature1\build\libs\core\coroutines\hpx_coroutines.dir\Debug\hpx_coroutines.lib
> ```

Could you try what happens if you add a `target_link_libraries(hpx_${libname} PRIVATE ${${modulename}_OBJECTS})` after this line?

> (side note: it's not quite clear why the two `.cpp` files are compiled separately outside the unity build - but that's unrelated).

Not quite clear to me either, in the sense that I couldn't figure out what was going wrong when they were included in the unity build. When they were included there were random segfaults (if I remember correctly) or assertions firing.

**Comment by hkaiser** [comment]
> > (side note: it's not quite clear why the two `.cpp` files are compiled separately outside the unity build - but that's unrelated).
> 
> Not quite clear to me either, in the sense that I couldn't figure out what was going wrong when they were included in the unity build. When they were included there were random segfaults (if I remember correctly) or assertions firing.

Ahh yes, I do remember now that you took those files explicitly out of the unity build.

**Comment by hkaiser** [comment]
> Could you try what happens if you add a `target_link_libraries(hpx_${libname} PRIVATE ${${modulename}_OBJECTS})` after this line:
> 
> https://github.com/STEllAR-GROUP/hpx/blob/ccc155e33287d967d3d5f3c942e4ad761669794c/cmake/HPX_AddModule.cmake#L424
> 
> ?

Yep, that fixed it. Thanks!

**Comment by hkaiser** [comment]
@msimberg thank you for looking into this!
