### PR TITLE
- bugfix : fix compilation with llvm-7.0

### LINKED ISSUE #3461: Compilation Problems with the most recent Clang
## Expected Behavior

HPX should compile normally, as it does when using an older clang version (as for example clang6, compiled with the same script mentioned below).

## Actual Behavior

When compiling clang (release_70 or HEAD), and in return using this clang to compile HPX I get the following the following error(s):

> /home/g/Work/tmp/octotiger-workspace/clang/include/c++/v1/iterator:1372:9: error: implicit instantiation of undefined template 'hpx::lcos::shared_future<hpx::naming::id_type>'
        ++__i;
        ^
/home/g/Work/tmp/octotiger-workspace/src/hpx/hpx/runtime/components/make_client.hpp:161:51: note: in instantiation of member function 'std::__1::__wrap_iter<hpx::lcos::shared_future<hpx::naming::id_type> *>::operator++' requested here
        for (hpx::shared_future<hpx::id_type>& id : ids)
                                                  ^
/home/g/Work/tmp/octotiger-workspace/src/hpx/hpx/lcos_fwd.hpp:61:15: note: template is declared here
        class shared_future;
              ^

For more information, I have attached to complete compilation log of HPX, and the CMakeOutput.log:
[CMakeOutput.log](https://github.com/STEllAR-GROUP/hpx/files/2402557/CMakeOutput.log)
[hpx_build_script_outputlog.txt](https://github.com/STEllAR-GROUP/hpx/files/2402559/hpx_build_script_outputlog.txt)

## Steps to Reproduce the Problem

The problem can best be reproduced by using the OctoTiger buildscripts. These will checkout and build clang (release_70), and use this clang to build all dependencies of OctoTiger, including HPX (master branch), in the current directory. Once the build script reaches HPX , it will fail with the error message mentioned earlier.

> 1. git clone https://github.com/G-071/OctotigerClangScripts.git octotiger-workspace
> 2. cd octotiger-workspace
> 3. ./build-all.sh RelWithDebInfo no-cuda

## Specifications

  - HPX Version: STEllAR-GROUP/hpx@61e7a441e4a1cbfe9647b4e45b2cbe3885d5f034
  - Platform: Ubuntu 18.04, Boost 1.65

### PR DESCRIPTION
**Pull request by jayeshbadwaik**
-    this bugfix allows hpx to compile with llvm-7.0. In the
    following places, full headers were needed but only fwd headers were
    used. Leading to compilation errors.

Fixes #3461 

## Proposed Changes

  - include full headers instead of fwd headers in `hpx/runtime/agas/interface.hpp` and `hpx/runtime/components/make_client.hpp`.

### CODE REVIEW

**Comment by hkaiser** [comment]
@jayeshbadwaik Thanks a lot for your contributions. We usually offer a free t-shirt to our first-contributors. If you're interested in receiving some nice STE||AR-Group swag please contact @aserio. He will arrange for one to be sent.

**Comment by aserio** [comment]
@jayeshbadwaik Please send me an email with your T-shirt size and address so that I can send you swag. You can see a size chart here: https://www.customink.com/items/sizing/172100_lineup/standard.htm
