### ISSUE TITLE
CMake issues with HPX 1.4.1

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/hpx#4418]
Has there been any changes with HPX/CMAKE. I ask because I have a simple hpx test application that works with 1.3 but not with 1.4.1. 
I am testing a simple hpx application using parallel for loops. It compiles and works fine with hpx 1.3 but fails to compile with hpx 1.4.1. 

Here is my project structure:
~/CLionProjects/hpx_test_project  tree
.
|____[main.cpp](https://gist.github.com/justwagle/8e98a911da1a56bee81da7d84a4cbeb4)
|____[CMakeLists.txt ](https://gist.github.com/justwagle/9703099aaa17381b647132186ac66ca9)
|____inside
|               |____[inside.cpp](https://gist.github.com/justwagle/fe72c0384c2310f66271eb987f4c203a)
|               |____[inside.hpp](https://gist.github.com/justwagle/e747cf79d8672f30565af73ce9349d17)
|               |____[CMakeLists.txt](https://gist.github.com/justwagle/2e169dc12dddd5fc8d22642ea5de8eff)

Basically the root directory has main.cpp and CMakeLists.txt. There is another directory inside the root directory called inside which has inside.cpp and inside.hpp. 

The contents of each files can be viewed by clicking on the filesnames in the  above project structure. 

## Expected Behavior

Appliation should compile with the above cmake files with HPX 1.4.1

## Actual Behavior

Appliation compiles with the above cmake files with HPX 1.3 but not with HPX 1.4.1
The error is get is:
``` 
/home/bibek/CLionProjects/hpx_test_project/inside/inside.hpp:1:45: fatal error: hpx/include/parallel_for_loop.hpp: No such file or directory
 #include <hpx/include/parallel_for_loop.hpp>
```

## Steps to Reproduce the Problem

Create a project with structure above. I called it source and is attached below. 
[source.zip](https://github.com/STEllAR-GROUP/hpx/files/4277510/source.zip)

Build using the following options:
```
cmake -Hsource -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release -DHPX_DIR=/opt/hpx/1.4.1/Release/install/lib/cmake/HPX/ 

cmake --build cmake-build-release
```

## Specifications
  - HPX Version: 1.3 / 1.4.1
  - Platform (compiler, OS): Ubuntu 18.04 / GCC 6.5.0 / Boost 1.65.1

**Comment by hkaiser** [comment]
@aurianer would you have the time to look into this?

**Comment by aurianer** [comment]
Yep sorry for being so slow to answer, I'm taking a look

**Comment by aurianer** [comment]
@justwagle, does  #4420 works for you ?

**Comment by justwagle** [comment]
@aurianer Yes, that worked for me, thanks.

**Comment by msimberg** [comment]
@justwagle the code did indeed work in 1.3.0 but only by chance. You should explicitly link `inside` to HPX, either by `target_link_libraries(inside PUBLIC ${HPX_LIBRARIES})`, `hpx_setup_target`, or `add_hpx_library`. Also having a global `include_directories` is not recommended as it affects every target in the project. Would you mind trying that first?

**Comment by justwagle** [comment]
@msimberg Thanks a lot. target_link_libraries(...) worked for me. I am closing the issue.
