### ISSUE TITLE
make tests failing at hello_world_component

### ISSUE THREAD

**Issue by Anushi1998** [STEllAR-GROUP/hpx#3290]
`make tests` is giving following error at commit `bee515038e`
```
libhpx_hello_world_component.so: undefined reference to `hpx::cout'
collect2: error: ld returned 1 exit status
CMakeFiles/hello_world_client.dir/build.make:127: recipe for target 'hello_world_client' failed
make[6]: * [hello_world_client] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hello_world_client.dir/all' failed
make[5]: * [CMakeFiles/hello_world_client.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make[4]: * [all] Error 2
tests/unit/build/CMakeFiles/cmake_build_dir_test.make_compile.dir/build.make:57: recipe for target 'tests/unit/build/CMakeFiles/cmake_build_dir_test.make_compile' failed
make[3]: * [tests/unit/build/CMakeFiles/cmake_build_dir_test.make_compile] Error 2
CMakeFiles/Makefile2:28127: recipe for target 'tests/unit/build/CMakeFiles/cmake_build_dir_test.make_compile.dir/all' failed
make[2]: * [tests/unit/build/CMakeFiles/cmake_build_dir_test.make_compile.dir/all] Error 2
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/tests.dir/rule' failed
make[1]: * [CMakeFiles/tests.dir/rule] Error 2
Makefile:266: recipe for target 'tests' failed
make: * [tests] Error 2
```

But `make tests` are passing at commit `69100ee061` successfully.

**Comment by NK-Nikunj** [comment]
@Anushi1998 seems like it's happening with gcc. The circle script with clang runs just fine.

**Comment by arkantos493** [comment]
I got the same error while linking hello_world_client in make tests.
(mak example completed successfully)

Is there any fix for this problem?

I'm using g++ 8.1.0 with the HPX Version 1.1.0 downloaded from the Ste||ar site. Boost 1.68.0 was build with c++std=17 and cmake ist up-to-date with version 3.13.0-rc2.

**Comment by NK-Nikunj** [comment]
@arkantos493 are you using the current master? In case your commit is of version 1.1.0, it will throw a linking error since this error was discovered later (hence part of the milestones for version 1.2).

**Comment by arkantos493** [comment]
@NK-Nikunj That might be the problem. So now I cloned the current git repo, but it appears that now not even the normal make is successfully:

> In member function ‘int hpx::threads::topology::get_numa_domain(const void*) const’:
../hpx/src/runtime/threads/topology.cpp:1332:13: error: ‘HWLOC_MEMBIND_BYNODESET’ was not declared in this scope
             HWLOC_MEMBIND_BYNODESET);
             ^~~~~~~~~~~~~~~~~~~~~~~
../hpx/src/runtime/threads/topology.cpp:1332:13: note: suggested alternative: ‘HWLOC_MEMBIND_PROCESS’
             HWLOC_MEMBIND_BYNODESET);
             ^~~~~~~~~~~~~~~~~~~~~~~
             HWLOC_MEMBIND_PROCESS
../hpx/src/runtime/threads/topology.cpp:1331:19: error: ‘hwloc_get_area_memlocation’ was not declared in this scope
         int ret = hwloc_get_area_memlocation(topo, addr, 1,  ns,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
../hpx/src/runtime/threads/topology.cpp:1331:19: note: suggested alternative: ‘hwloc_get_area_membind’
         int ret = hwloc_get_area_memlocation(topo, addr, 1,  ns,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   hwloc_get_area_membind
src/CMakeFiles/hpx.dir/build.make:1297: recipe for target 'src/CMakeFiles/hpx.dir/runtime/threads/topology.cpp.o' failed
make[2]: *** [src/CMakeFiles/hpx.dir/runtime/threads/topology.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1828: recipe for target 'src/CMakeFiles/hpx.dir/all' failed
make[1]: *** [src/CMakeFiles/hpx.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error

I tried setting hwloc manually with the -DHWLOC_ROOT cmake flag and using the default version without flag.

**Comment by msimberg** [comment]
What version of hwloc are you using?

**Comment by arkantos493** [comment]
Thanks for the reply. I used hwloc 1.11 from the apt repositories. After I manually installed version 2.0.2 it worked.

**Comment by msimberg** [comment]
@arkantos493 thanks for reporting back. Could you also tell me the patch number of the 1.11 version that you tried? Our build *should* work with any 1.11 but that doesn't seem to be the case.

**Comment by msimberg** [comment]
Thanks @arkantos493, in that case your problem should be solved now that #3528 has been merged.
