### ISSUE TITLE
HPX fails to build with gcc 6.5.0

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4408]
## Expected Behavior

Until about a month ago, HPX could build with gcc 6.5.0:
http://omega.nic.uoregon.edu:8010/#/builders/2

## Actual Behavior

Compilation error:

```console
[  6%] Building CXX object libs/serialization/CMakeFiles/hpx_serialization.dir/src/detail/pointer.cpp.o
In file included from /home/khuck/src/xpress-apex/K-hpx-debug/noapex/libs/debugging/include/hpx/debugging.hpp:13:0,
                 from /dev/shm/khuck/hpx/libs/serialization/include/hpx/serialization/detail/polymorphic_intrusive_factory.hpp:13,
                 from /dev/shm/khuck/hpx/libs/serialization/include/hpx/serialization/detail/polymorphic_id_factory.hpp:16,
                 from /dev/shm/khuck/hpx/libs/serialization/include/hpx/serialization/detail/pointer.hpp:15,
                 from /dev/shm/khuck/hpx/libs/serialization/src/detail/pointer.cpp:10:
/dev/shm/khuck/hpx/libs/debugging/include/hpx/debugging/print.hpp:422:24: error: enclosing class of constexpr non-static member function ‘bool hpx::debug::enable_print<true>::is_enabled() const’ is not a literal type
         constexpr bool is_enabled() const
                        ^~~~~~~~~~
/dev/shm/khuck/hpx/libs/debugging/include/hpx/debugging/print.hpp:411:12: note: ‘hpx::debug::enable_print<true>’ is not literal because:
     struct enable_print<true>
            ^~~~~~~~~~~~~~~~~~
/dev/shm/khuck/hpx/libs/debugging/include/hpx/debugging/print.hpp:411:12: note:   ‘hpx::debug::enable_print<true>’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
libs/serialization/CMakeFiles/hpx_serialization.dir/build.make:62: recipe for target 'libs/serialization/CMakeFiles/hpx_serialization.dir/src/detail/pointer.cpp.o' failed
make[2]: *** [libs/serialization/CMakeFiles/hpx_serialization.dir/src/detail/pointer.cpp.o] Error 1
CMakeFiles/Makefile2:42258: recipe for target 'libs/serialization/CMakeFiles/hpx_serialization.dir/all' failed
make[1]: *** [libs/serialization/CMakeFiles/hpx_serialization.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  configure: 
```
cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/usr/local/boost/1.65.0-gcc6 -DTCMALLOC_ROOT=/usr/local/gperftools/2.5 -DHPX_WITH_MALLOC=tcmalloc -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=OFF -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=ON -DHPX_WITH_TOOLS=OFF -DHPX_WITH_STACKOVERFLOW_DETECTION_DEFAULT=OFF /dev/shm/khuck/hpx
```
  1.  make 
  1.

## Specifications

... Please describe your environment

  - HPX Version: latest master
  - Platform (compiler, OS):  linux ubuntu 16, gcc 6.5.3

**Comment by hkaiser** [comment]
@khuck with the move to require (full) C++14 support for HPX starting the next release, we will have to cut down on supported compilers. Apparently, we will have to stop supporting gcc 6.x as well.

**Comment by khuck** [comment]
@hkaiser no problem - more motivation to update that machine.  :)

**Comment by msimberg** [comment]
@khuck I'll close this as I've made the requirement official with #4425.
