### ISSUE TITLE
HPX does not build with Boost 1.58.0

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#1527]
I am trying to build HPX 0.9.10 with Boost 1.58.0. This is on OS X using clang 3.6.0. The build aborts with the error message
```
/Users/eschnett/software/boost-1.58.0/include/boost/serialization/vector.hpp:216:18: error: comparison of integers of different signs: 'int' and 'base_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
    for(i = 0; i < count; ++i){
               ~ ^ ~~~~~
```
This looks as if Boost misbehaved, iterating over the element of `std::vector` using `int` (why???). HPX then adds `-Werror` to the mix, leading to this build failure.

It is customary to disable `-Werror` in released versions for this reason.

This problem sounds oddly familiar; was this discussed before?

**Comment by hkaiser** [comment]
You reported that before (see #1475). As said, Boost V1.58 was not released at the point when we released HPX V0.9.10.

**Comment by hkaiser** [comment]
Until the next release of HPX please patch your local copy of HPX by removing the `-Werror` flag locally (https://github.com/STEllAR-GROUP/hpx/blob/0.9.10/CMakeLists.txt#L818).
