### ISSUE TITLE
undeclared identifier BOOST_COMPILER_FENCE

### ISSUE THREAD

**Issue by K-ballo** [STEllAR-GROUP/hpx#2441]
Boost.SmartPtr does not define the implementation detail macro `BOOST_COMPILER_FENCE` when implementing its spinlock on top of `std::atomic` primitives. This results in compilation errors for VS2015 and Boost 1.63.0, where using `std::atomic` instead of win32 primitives appears to be the new default. The issue should be reproducible on any windows build with Boost 1.56.0+ by forcing the use of `std::atomic` via `BOOST_SP_USE_STD_ATOMIC`.

**Comment by K-ballo** [comment]
The commit that caused the issue to be exposed is https://github.com/boostorg/smart_ptr/commit/20fedcff2ca3143503ec4e876d47745ab0ec7b0c
