### ISSUE TITLE
HPX does not compile with MSVC of Visual Studio 2022 17.9+

### ISSUE THREAD

**Issue by BillyONeal** [STEllAR-GROUP/hpx#6440]
## Steps to Reproduce the Problem

`vcpkg install hpx:x64-windows`

```console
D:\vcpkg\buildtrees\hpx>C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\cl.exe /TP -DBOOST_ALL_NO_LIB -DHPX_DEBUG -DHPX_FULL_EXPORTS -D_WIN32 -D_WINDOWS [a million /Is skipped here] -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 -MDd -Zc:inline -Zc:throwingNew -Zc:rvalueCast -Zc:strictStrings -Zc:__cplusplus -GR -MP -bigobj -permissive- -EHsc -W3 -wd4180 -wd4307 -wd4316 -wd4503 -wd4800 -wd4828 -wd4848 -FC /diagnostics:caret /Folibs\full\collectives\CMakeFiles\hpx_collectives.dir\src\detail\barrier_node.cpp.obj /Fdlibs\full\collectives\Debug\hpx_collectivesd.pdb /FS -c D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\full\collectives\src\detail\barrier_node.cpp

barrier_node.cpp
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_traits.hpp(76,61): error C2794: 'type': is not a member of any direct or indirect base class of 'hpx::traits::future_traits<void>'
    using future_traits_t = typename future_traits<Future>::type;
                                                            ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_traits.hpp(76,61): note: the template instantiation context (the oldest one first) is
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\full\collectives\src\detail\barrier_node.cpp(225,19): note: see reference to function template instantiation 'hpx::future<void> hpx::future<void>::then<const hpx::detail::sync_policy&,hpx::distributed::detail::barrier_node::do_wait::<lambda_3>>(T0,F &&,hpx::error_code &)' being compiled
        with
        [
            T0=const hpx::detail::sync_policy &,
            F=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
            future.then(hpx::launch::sync, [this_](hpx::future<void>&& f) {
                  ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\future.hpp(1013,31): note: see reference to function template instantiation 'hpx::future<void> hpx::lcos::detail::future_base<hpx::future<void>,R>::then<_Ty,const hpx::detail::sync_policy&>(Derived &&,T0,F &&,hpx::error_code &)' being compiled
        with
        [
            R=void,
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Derived=hpx::future<void>,
            T0=const hpx::detail::sync_policy &,
            F=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
            return base_type::then(
                              ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\future.hpp(622,60): note: see reference to function template instantiation 'hpx::future<void> hpx::lcos::detail::future_then_dispatch<Derived,F,void>::call<const hpx::detail::sync_policy&,_Ty>(Future &&,Policy_,hpx::distributed::detail::barrier_node::do_wait::<lambda_3> &&)' being compiled
        with
        [
            Derived=hpx::future<void>,
            F=hpx::detail::sync_policy,
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Future=hpx::future<void>,
            Policy_=const hpx::detail::sync_policy &
        ]
            return future_then_dispatch<std::decay_t<T0>>::call(
                                                           ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\execution\include\hpx\execution\detail\future_exec.hpp(64,25): note: see reference to function template instantiation 'hpx::intrusive_ptr<hpx::lcos::detail::future_data_base<hpx::traits::detail::future_data_void>> hpx::lcos::detail::make_continuation_alloc<continuation_result_type,std::allocator<int>,hpx::future<void>,const hpx::detail::sync_policy&,_Ty>(const Allocator &,Future &&,Policy,F &&)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Allocator=std::allocator<int>,
            Future=hpx::future<void>,
            Policy=const hpx::detail::sync_policy &,
            F=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
                detail::make_continuation_alloc<continuation_result_type>(
                        ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\execution\include\hpx\execution\detail\future_exec.hpp(227,44): note: see reference to function template instantiation 'void hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::attach<true,spawner_type,hpx::future<void>,const hpx::detail::sync_policy&>(Future_ &&,Spawner &&,Policy,hpx::error_code &)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Future_=hpx::future<void>,
            Spawner=spawner_type,
            Policy=const hpx::detail::sync_policy &
        ]
        static_cast<shared_state*>(r.get())->template attach<true>(
                                           ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(325,30): note: see reference to function template instantiation 'void hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::async<true,hpx::lcos::detail::post_policy_spawner>(hpx::intrusive_ptr<hpx::lcos::detail::future_data_base<hpx::traits::detail::future_data_void>> &&,Spawner &&)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Spawner=spawner_type
        ]
                        this_->template async<Unwrap>(
                             ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(325,54): note: see the first reference to 'hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::async' in 'hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::attach::<lambda_1>::operator ()'
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
                        this_->template async<Unwrap>(
                                                     ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(234,26): note: see reference to function template instantiation 'void hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::run_impl<true>(hpx::intrusive_ptr<hpx::lcos::detail::future_data_base<hpx::traits::detail::future_data_void>> &&)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
                    this_->template run_impl<Unwrap>(HPX_MOVE(f));
                         ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(234,53): note: see the first reference to 'hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::run_impl' in 'hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::async::<lambda_1>::operator ()'
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>
        ]
                    this_->template run_impl<Unwrap>(HPX_MOVE(f));
                                                    ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(207,17): note: see reference to function template instantiation 'void hpx::lcos::detail::invoke_continuation<hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,hpx::future<void>,hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>>(Func &,Future &&,Continuation &)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Func=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Future=hpx::future<void>,
            Continuation=hpx::lcos::detail::continuation<hpx::future<void>,hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,result_type>
        ]
                invoke_continuation(f_, HPX_MOVE(future), *this);
                ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(91,41): note: see reference to alias template instantiation 'hpx::traits::detail::shared_state_ptr_for_t<inner_future>' being compiled
                        traits::detail::shared_state_ptr_for_t<inner_future>;
                                        ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(99,52): note: see reference to class template instantiation 'hpx::traits::detail::shared_state_ptr_for<inner_future,void>' being compiled
            typename shared_state_ptr_for<Future>::type;
                                                   ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(69,25): note: see reference to alias template instantiation 'hpx::traits::future_traits_t<void>' being compiled
                traits::future_traits_t<std::remove_const_t<Future>>>
                        ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(69,25): error C2938: 'hpx::traits::future_traits_t' : Failed to specialize alias template
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(68,13): error C2976: 'hpx::traits::detail::shared_state_ptr': too few template arguments
          : shared_state_ptr<
            ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(55,16): note: see declaration of 'hpx::traits::detail::shared_state_ptr'
        struct shared_state_ptr
               ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(68,13): error C2955: 'hpx::traits::detail::shared_state_ptr': use of class template requires template argument list
          : shared_state_ptr<
            ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(55,16): note: see declaration of 'hpx::traits::detail::shared_state_ptr'
        struct shared_state_ptr
               ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\traits\future_access.hpp(99,52): error C2794: 'type': is not a member of any direct or indirect base class of 'hpx::traits::detail::shared_state_ptr_for<inner_future,void>'
            typename shared_state_ptr_for<Future>::type;
                                                   ^
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\futures\include\hpx\futures\packaged_continuation.hpp(91,41): error C2938: 'hpx::traits::detail::shared_state_ptr_for_t' : Failed to specialize alias template
                        traits::detail::shared_state_ptr_for_t<inner_future>;
                                        ^
```

## Specifications

  - HPX Version: 1.9.1
  - Platform (compiler, OS): MSVC 19.39.33519

I've spent about 2 hours trying to look at this and have made no meaningful progress. I think something is going wrong at the:

```console
D:\vcpkg\buildtrees\hpx\src\v1.9.1-d67aefad9f.clean\libs\core\execution\include\hpx\execution\detail\future_exec.hpp(227,44): note: see reference to function template instantiation 'void hpx::lcos::detail::continuation<hpx::future<void>,_Ty,result_type>::attach<true,spawner_type,hpx::future<void>,const hpx::detail::sync_policy&>(Future_ &&,Spawner &&,Policy,hpx::error_code &)' being compiled
        with
        [
            _Ty=hpx::distributed::detail::barrier_node::do_wait::<lambda_3>,
            Future_=hpx::future<void>,
            Spawner=spawner_type,
            Policy=const hpx::detail::sync_policy &
        ]
        static_cast<shared_state*>(r.get())->template attach<true>(
```

step, since `true` here tells `attach` to 'unwrap', as if the callable returned future and this was doing the `future<future<T>> -> future<T>` transformation. Because 'attach = true' seems to call:

```c++
    template <typename Func, typename Future, typename Continuation>
    void invoke_continuation(Func& func, Future&& future, Continuation& cont)
    {
        using inner_future = util::invoke_result_t<Func, Future>;
```

as in, this is assuming that the callable returns another future. But this callable returns void, not another future type, so trying to ask future questions of it explodes.

But I super don't know what I'm doing here.....

**Comment by BillyONeal** [comment]
(I think this is probably a compiler bug but after spending 3.5 hours trying to figure out where it's going wrong I'm not sure how to reduce this)

**Comment by hkaiser** [comment]
@BillyONeal would you mind trying HPX master?

**Comment by BillyONeal** [comment]
Interesting, master passes. I'm almost certain it's a compiler bug but I'm having difficulty reducing it...

**Comment by BillyONeal** [comment]
Heh, I bet fixed by https://github.com/STEllAR-GROUP/hpx/commit/6c378813a7e2304a3a0c8900156f147a3a44b0cb

**Comment by BillyONeal** [comment]
Thanks @hkaiser

**Comment by hkaiser** [comment]
> Thanks @hkaiser

Thank _you_ @BillyONeal!
